spring:
  datasource:
    url: jdbc:sqlserver://firstcompany.database.windows.net:1433;database=Company;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: firstcompany
    password: SpringBoot@7877
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8086
  
